package ${package}.controllers;

import ${package}.autogenerated.api.SampleApi;
import ${package}.autogenerated.dto.SampleDto;
import ${package}.services.SampleService;
import io.swagger.annotations.Api;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@Api(tags = "sample")
@RestController
public class SampleController implements SampleApi {

	private final SampleService sampleService;

	public SampleController(SampleService sampleService) {

		this.sampleService = sampleService;
	}

	@Override
	public ResponseEntity<List<SampleDto>> getSamples() {
		return ResponseEntity.ok(sampleService.getAll());
	}

	@Override
	public ResponseEntity<SampleDto> getSampleById(Long id) {
		return ResponseEntity.ok(sampleService.getOne(id));
	}
}
