package ${package}.services;

import ${package}.autogenerated.dto.SampleDto;
import ${package}.mappers.SampleMapper;
import ${package}.repositories.SampleRepository;
import org.springframework.stereotype.Service;

import javax.persistence.EntityNotFoundException;
import java.util.List;

@Service
public class SampleService {

	private final SampleRepository sampleRepository;
	private final SampleMapper sampleMapper;

	public SampleService(SampleRepository sampleRepository, SampleMapper sampleMapper) {
		this.sampleRepository = sampleRepository;
		this.sampleMapper = sampleMapper;
	}

	public List<SampleDto> getAll() {
		return sampleMapper.toListDto(sampleRepository.findAll());
	}

	public SampleDto getOne(Long id) {
		return sampleMapper.toDto(sampleRepository.findById(id).orElseThrow(EntityNotFoundException::new));
	}
}
