openapi: "3.0.0"
info:
    title: Swagger Application
    description: This is Application server.
    termsOfService: "http://swagger.io/terms/"
    contact:
        email: firstname.lastname@capgemini.com
    license:
        name: Apache 2.0
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    version: "1.0.0"
servers:
    - url: "{protocol}://{host}:{port}"
      variables:
          protocol:
              enum:
                  - "http"
                  - "https"
              default: "http"
          port:
              enum:
                  - "8080"
                  - "8443"
              default: "8080"
          host:
              enum:
                  - "localhost"
              default: "localhost"
tags:
    - name: app
      description: Informations about application
    - name: sample
      description: Operations about Sample
paths:
    "/api":
        get:
            tags:
                - app
            summary: Get API status
            operationId: getStatus
            responses:
                "200":
                    description: An API status
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AppStatus"
                "400":
                    description: Bad request
                    content: {}
                "404":
                    description: Error
                    content: {}
    "/api/v1/samples":
        get:
            tags:
                - sample
            summary: Get all samples
            operationId: getSamples
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Sample"
                "400":
                    description: Invalid request format
                    content: {}
    "/api/v1/samples/{sampleId}":
        get:
            tags:
                - sample
            summary: Get samples by sampleId
            operationId: getSampleById
            security:
                - bearerAuth: []
            parameters:
                - name: sampleId
                  in: path
                  description: 'The id that needs to be fetched. Use "1" for testing. '
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Sample"
                "400":
                    $ref: '#/components/responses/IvalidSampleId'
                "404":
                    $ref: '#/components/responses/SampleNotFound'
components:
    responses:
        SampleNotFound:
            description: Sample not found for given ID
            content: {}
        IvalidSampleId:
            description: Invalid sampleId supplied. Must be long type greater than 0.
            content: {}
    schemas:
        AppStatus:
            type: object
            properties:
                app-version:
                    type: string
                    description: https://schema.org/version
        Sample:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                value:
                    type: string